### ISSUE TITLE
Improve search_census_vectors and child_census_vectors functionality

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cancensus#119]
* Add functionality to search by CensusMapper internal census vector variable as additional option to pinpoint variables
* Add functionality to set maximum depth for child census vectors, i.e. `max_level=NA` as an additional parameter. Then e.g. `max_level=1` would only get direct children and no grandchildren.

**Comment by dshkol** [comment]
Let's commit to adding `child_census_vectors functionality` for next release.

Searching for CensusMapper internal variables will not be added

**Comment by mountainMath** [comment]
Added in 5ed8cbeeafaf9553e9eebe81b28339c6fcda51a3 in branch https://github.com/mountainMath/cancensus/tree/list-region-fix.

**Comment by dshkol** [comment]
Added in #123
