### ISSUE TITLE
Reproducibility issue in get_census

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#127]
Related to #126 

The following code throws a parsing error now.

```
dataset <- "CA16"

regions_list10 <- list_census_regions(dataset) %>% 
  filter(level=="CMA") %>% 
  top_n(10,pop) %>% 
  as_census_region_list

csd_geo <- get_census(dataset, level = 'CSD', regions = regions_list10)
```

> Warning: 1 parsing failure.
row  col expected    actual         file
  9 rpid a double s_1_35_35 literal data

Data looks fine in download, but the warning is unexpected.

This is from code written pre-CRAN release.

**Comment by mountainMath** [comment]
Hm. I don't get that warning. Can you refresh your cache?

**Comment by dshkol** [comment]
```
csd_geo <- get_census(dataset, level = 'Regions', regions = regions_list10, use_cache = FALSE)
```

>Querying CensusMapper API...
Downloading: 500 B     Warning: 1 parsing failure.
row  col expected    actual         file
  9 rpid a double s_1_35_35 literal data

Still there. 

This is cancensus 0.1.8

**Comment by mountainMath** [comment]
Fixed in https://github.com/mountainMath/cancensus/pull/123
