### ISSUE TITLE
Soft deprecate get_census_geometry

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#128]
See related #126 

This function is duplicated by just using `get_census` with geo parameters set and no variable parameters. 

We can soft deprecate this so it still works in legacy code but throws a warning on deprecation, and remove it from active documentation.

**Comment by mountainMath** [comment]
Addressed in https://github.com/mountainMath/cancensus/commit/093434d4731ef4d8982675becb4e3bf5c9d057a5 in branch https://github.com/mountainMath/cancensus/tree/list-region-fix and PR https://github.com/mountainMath/cancensus/pull/123
