### ISSUE TITLE
Create vignettes for CMHC data

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#140]
There's currently very little documentation on how to use the additional data open-sourced by CMHC used here: 
- https://doodles.mountainmath.ca/blog/2020/04/23/census-tract-level-t1ff-tax-data/
- https://doodles.mountainmath.ca/blog/2020/01/26/unoccupied-dwellings-data/

Can these articles be adapted into a vignette or two to include on the site and bundled with the package?

**Comment by mountainMath** [comment]
Good call, I will do that. Slightly related, there is another xtab, "Family Characteristics of Adults (11), Age (16) and Sex (3) for the Population 15 Years and Over in Private Households" that I imported at some point, goes down to CT level. But it's kind of niche, it's from when I was interested in young adults living with parents.

Not sure if it's worth exposing it through `cancensus`, nowadays I would provably recommend people just getting the xtab straight from StatCan using the [`statcanxtabs` package](https://github.com/mountainMath/statcanXtabs). Although that package would need some documentation and cleanup work. And somehow deal with the unzip issue on windows machines, and it also at this point requires python to parse large (e.g. 20GB) xml.

**Comment by dshkol** [comment]
Thanks, we can add that once ready. 

WRT the other dataset you mentioned - I think sometimes it's alright to let things be as they are. The complexity vs potential applications of an additional package or extending core functionality to fit that use case is probably not worth it. I think having a process document like you do somewhere for how to work with that particular xtab is sufficient.

**Comment by mountainMath** [comment]
Added a vignette for the structural type by document type to the [dplyr-deprecated branch](https://github.com/mountainMath/cancensus/tree/dplyr-deprecated). Will add a vignette for the tax data in the coming days.

**Comment by dshkol** [comment]
Added in #142
