### ISSUE TITLE
Consider moving away from Travis CI for CI 

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#159]
Let's check if we're affected by the upcoming changes to Travis for open-source projects and if doing so we cna adjust and use one of the recommended alternatives: https://ropensci.org/technotes/2020/11/19/moving-away-travis/

**Comment by boshek** [comment]
We've had pretty good success with GitHub actions. Since `{bcdata}` and `{cancensus}` have some similar elements our workflow might be of interest when you decide to tackle this: https://github.com/bcgov/bcdata/blob/master/.github/workflows/cmd-check.yaml

**Comment by mountainMath** [comment]
Addressed in https://github.com/mountainMath/cancensus/tree/intersect_geometry2

**Comment by mountainMath** [comment]
Done and merged into main.
