### ISSUE TITLE
Data for Census Agglomerations (CAs) without a census tract

### ISSUE THREAD

**Issue by lj-valencia** [mountainMath/cancensus#165]
I tried to use the list_census_regions('CA16') %>% filter (municipal_status = "D") to search for census agglomerations without census tracts as they're supposedly labelled with the type code "D". However, this query returned an empty tibble.

**Comment by mountainMath** [comment]
Unfortunately, CAs without census tracts currently aren't part of the data that is mirrored on CensusMapper and accessible through {cancensus}.

**Comment by lj-valencia** [comment]
Thank you for your reply! I will take note of this when using the package.
