### ISSUE TITLE
option to keep parent in output of child_census_vectors()

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#166]
I believe the most common use case for `child_census_vectors()` is to generate a list of downstream hierarchy vectors given an input and it works well there. One version of this that frequently comes up is to calculate proportions by dividing the children values by the upstream parent one. This is easy enough to do as is, but requires appending the parent vector to the result of the call. We can streamline this a bit by including an option like `'keep_parent = TRUE` in the call to retain the parent vector as well.

**Comment by mountainMath** [comment]
Sounds good to me. I usually solve this by doing `%>% bind_rows(child_census_vectors(.))` if I want to keep the parent, but I agree that having an option makes this cleaner and more transparent.

**Comment by dshkol** [comment]
On this, we should also just give an option to return the vector codes only. I do this basically everytime: `%>% 
  pull(vector))`

**Comment by dshkol** [comment]
This was added in #167
