### ISSUE TITLE
CRAN: error handling of STC certificate issues  

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#170]
Seems once again CRAN maintainers are unhappy with errors due to examples failing due to SSL errors on Statistics Canada content. 

```
Please correct before 2021-05-30 to safely retain your package on CRAN.

It seems we need to remind you of the CRAN policy:

'Packages which use Internet resources should fail gracefully with an informative message
if the resource is not available or has changed (and not give a check warning nor error).'

This needs correction whether or not the resource recovers.
```

```
Version: 0.4.2
Check: examples
Result: ERROR
    Running examples in ‘cancensus-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: child_census_vectors
    > ### Title: List all child variables from vector hierarchies given either a
    > ### list of Census variables returned by 'list_census_vectors',
    > ### 'search_census_vectors', 'find_census_vectors', or a direct string
    > ### reference to the vector code.
    > ### Aliases: child_census_vectors
    >
    > ### ** Examples
    >
    > # Query parent vectors directly using vector identifier
    > child_census_vectors("v_CA16_2510")
    Error in curl::curl_fetch_memory(url, handle = handle) :
     SSL certificate problem: certificate has expired
    Calls: child_census_vectors ... request_fetch -> request_fetch.write_memory -> <Anonymous>
    Execution halted
```

**Comment by mountainMath** [comment]
That's a CensusMapper problem. Fixed now. The certificates get renewed automatically, but the web server does not get reloaded automatically. And sometimes I forget to do that manually. I really need to set this up to be fully automated.

**Comment by dshkol** [comment]
should we still do something on the package side for it "fail gracefully" as requested?

**Comment by mountainMath** [comment]
Maybe at some point? Not sure what “gracefully” means here, it should throw an error and stop execution when it can’t get the data. I think I just need to make sure the certificate on the server is fully automated.

**Comment by dshkol** [comment]
Seems errors are still there on the check page. 

https://cran.r-project.org/web/checks/check_results_cancensus.html

I'm not sure if the tests have been re-run since your fix or not.

**Comment by mountainMath** [comment]
Pretty sure it just hasn't been re-run.

**Comment by mountainMath** [comment]
One way to fix this long term is to also exclude that vignette from compilation. Also, we could add a nightly GitHub action to run checks, that way we get notified early if there are any issues coming up.

**Comment by dshkol** [comment]
The error checks have come up clean now as predicted. I don't think this needs any changes, but let's get an update up to CRAN before the 31st with other changes.
