### ISSUE TITLE
Broken Links in Vignette?

### ISSUE THREAD

**Issue by swaheera** [mountainMath/cancensus#178]
Hello!

I was looking at some of the vignettes - here was the trail I followed:

https://github.com/mountainMath/cancensus -> https://www.dshkol.com/2017/language-diversity-in-canada/ -> https://github.com/dshkol/scratchpad/blob/master/content/post/2017-10-02-language-diversity-in-canada.Rmd 

The final link (i.e. https://github.com/dshkol/scratchpad/blob/master/content/post/2017-10-02-language-diversity-in-canada.Rmd) appears to be broken. 

Has it moved to a new location?

Thanks!

PS: This is a GREAT R package! Excellent work - all of you!

**Comment by mountainMath** [comment]
Looks like the link in the blog is broken @dshkol? Looking into the repo, I believe it should be
https://github.com/dshkol/scratchpad/blob/master/content/2017/2017-10-02-language-diversity-in-canada.Rmd
instead of
https://github.com/dshkol/scratchpad/blob/master/content/post/2017-10-02-language-diversity-in-canada.Rmd
.

**Comment by dshkol** [comment]
Very possible. I did some kind of restructuring on the site a year or so
ago that probably caused that. Lots of little things to fix.

**Comment by swaheera** [comment]
@mountainMath  and @dshkol  : thank you so much! 

I wonder if I were to change the format of the old hyperlinks to the new hyperlink pattern, will I find the correct links for all R code used in these tutorials?

Thanks so much everyone!

**Comment by mountainMath** [comment]
If some of the links on @dshkol's blog linking to the source notebooks are broken you can check through the repo to locate the correct Rmd file. This directory is probably a good start.
https://github.com/dshkol/scratchpad/tree/master/content
