### ISSUE TITLE
Add discoverability for datasets

### ISSUE THREAD

**Issue by atheriel** [mountainMath/cancensus#18]
The package's main function currently accepts a `datasets` parameter that specifies which census to query, one of `c("CA16", "CA11", "CA06")` at the moment. It would be nice if there was some way for users to "discover" what data were available, for example with a function like

```r
> cancensus::list_datasets()
# # A tibble: 3 x 2
#   dataset                    description
#     <chr>                          <chr>
# 1    CA16                    2016 Census
# 2    CA11 2011 National Household Survey
# 3    CA06                    2006 Census
```

As I said via email, I think there are two ways of doing this, either (1) adding a `datasets` endpoint to the API that would return this kind of information, and/or (2) just hardcoding it into the package for now.

**Comment by mountainMath** [comment]
That's a good idea, will implement the server side code for this.

**Comment by mountainMath** [comment]
I added a quick endpoint https://censusmapper.ca/api/v1/list_datasets that returns a JSON array.

**Comment by atheriel** [comment]
I whipped up a quick wrapper matching the proposal above. See #20.
