### ISSUE TITLE
Duplicate vector numbers

### ISSUE THREAD

**Issue by QU4N7UM** [mountainMath/cancensus#186]
Hi there,
I noticed that vectors v_CA21_983 / 996 / 1062 have duplicate values.
Unless I'm mistaken, one of the duplicated 983 might be 993, one of the duplicated 996 should be 997 and one of the duplicated 1062 should be 1061?
This does affect data loading if we use, for example, a list of vectors (e.g. in an Excel file) previously extracted and filtered for our needs. An error is raised saying something like no duplicate values allowed in vectors.
It also seems to return only one of the two vectors (not really knowing which when labels = "short") when requesting these vectors.

**Comment by mountainMath** [comment]
Thanks for flagging this! This is a bug in CensusMapper metadata. There is a problem with the internal naming/labelling of variables.

I have fixed the error and added the three variables to the recall list in case someone has downloaded data with these variables it will warn them and ask them clear them from the local cache next time a new R session is started and census data is queried. (Fortunately nobody used any of these variables in live CensusMapper maps, so no problem there.)
