### ISSUE TITLE
Responses get_census() function are just integers divisibles by 5 or "rounded"

### ISSUE THREAD

**Issue by bwcastillo** [mountainMath/cancensus#193]
Hello, 

I am trying to get data from cancensus (Census 2021) either, spatial or tabular format through `get_cesus()`  function, and the data recovered is just multiples of 5. I could verify this inconsistency through **_Total Population_** variable (attached), only _**Total Dwellings**_  variable looks consistent. 

```
get_census(dataset='CA21',
                        regions= list(DA=area_da_binary$DAUID), 
                        vector=vector21reep,     #List of variables 
                        level="DA",       
                    #   geo_format = "sf",       #I tried not using sf to see if tabular format change   
                        use_cache = F)           #I tried not using the cache to see if it change
```

Both images are a screenshot from the same dataframe:

1)Information obtained by default (**_Population_**)

<img width="441" alt="1" src="https://user-images.githubusercontent.com/24574446/206317632-01efeeb1-3f1a-4337-919b-440b062c31d0.png">

2)Information in the query (_**vCA21_8: Total-Age**_)
<img width="499" alt="2" src="https://user-images.githubusercontent.com/24574446/206317634-32cddbb0-2080-4e9a-b66a-f352b28f670e.png">

I hope to know how is possible to resolve it. 

Thanks in advance for you work. 

PS: I love this library. Thank you again.

**Comment by mountainMath** [comment]
The only variables that StatCan releases without statistical rounding are Population, Dwellings, and Household counts, and they are automatically attached to the result of any `get_census()` call. All variables that are part of the "100% data" or "25% data" undergo statistical rounding and are not available as raw counts.

**Comment by bwcastillo** [comment]
@mountainMath 

Thank you so much for the early/fast response, I really appreciate that. 

Effectively, it happens I did some test with the API and is what you said. But, still curious I evaluated each variable that says 100%, and _Apartment in a building that has five or more storeys_ and _Neither English nor French_  returned just multiples by 5, maybe the question in the census form is like that, or is just coincidence. 


<img width="489" alt="3" src="https://user-images.githubusercontent.com/24574446/206591486-5def5118-8d39-4347-883f-03bbf87badb0.png">

```
#Values in the census 2021 file 98-401-X2021006_English_meta.txt
var2021<-paste0(c("4","8","47","229","346","373"),collapse ="+") 

#DA's of interests
da2021<-paste0(area_da_geometry$DGUID[1:200], collapse="+") #Just 200

#Query to the API 
rsdmx2021da<-as.data.frame(readSDMX(paste0("https://api.statcan.gc.ca/census-recensement/profile/sdmx/rest/data/STC_CP,DF_DA/A5.",da2021,"..",var2021,".1")))
rsdmx2021da$CHARACTERISTIC<-as.numeric(rsdmx2021da$CHARACTERISTIC)
class(rsdmx2021da$CHARACTERISTIC) #characters 
View(rsdmx) #Doing filters in the data frame GUI

#Still multiples of 5 even in API response:
#47 (Apartment in a building that has five or more storeys: v_CA21_440) 
#373 (Neither English nor French: v_CA21_1156)

```

Thank you again. 
This library is brilliant.
