### ISSUE TITLE
[feature request] querying shapes directly

### ISSUE THREAD

**Issue by 18kimn** [mountainMath/cancensus#197]
I'm interested in querying census boundary files directly, but this is only possible with `cancensus` if we query census data alongside it. Could this logic be separated and a dedicated function be exposed for shapefile access?

I'm not really sure how the underlying API works and if CensusMapper supports such a call, so please feel free to close in that case

**Comment by mountainMath** [comment]
In a call with an empty `vectors` argument you will just get the geographic data, plus population, household and dwelling counts.

If you are interested in comprehensive geographic data, starting version 0.5.5 there is the option to query comprehensive geography files directly from StatCan for the 2021 census using [`get_statcan_geographies()`](https://mountainmath.github.io/cancensus/reference/get_statcan_geographies.html).

**Comment by 18kimn** [comment]
ah fantastic, thank you!
