### ISSUE TITLE
rgdal and rgeos dependencies

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cancensus#201]
[rgdal and rgeos won't be available on CRAN after October 2023](https://geocompx.org/post/2023/rgdal-retirement/), but are part of the **cancensus** dependencies. It should not be a big deal to replace the dependencies, but this might mean not supporting **sp** data output any more. Since **sf** is well-established now this should not be an issues, people wanting data in **sp** format can simply call `as(.,"Spatial")` after getting **sf** data from **cancensus**.

**Comment by mountainMath** [comment]
Removed the **rgdal** and **rgeos** dependencies and all checks passed. Looks like they were just legacy dependencies that probably became obsolete after the latest changes that just use **sp** to cast the **sf** object at the last moment. Tested querying data in **sp** format with getting the **rgdal** and **rgeos** packages removed and it all works fine.

So only thing left to do is ensure that branch https://github.com/mountainMath/cancensus/tree/v0.5.6 gets merged before October.

**Comment by olivroy** [comment]
@mountainMath do you still plan to submit ? I think the retirement date is Oct 16, 2023

**Comment by mountainMath** [comment]
Yes, thanks for the reminder. Planning on submitting today.
