### ISSUE TITLE
Add discoverability for vectors and regions

### ISSUE THREAD

**Issue by atheriel** [mountainMath/cancensus#26]
We discussed this via email, but I think it is worth filing an issue to highlight that this is a desired feature. Something like the current `list_datasets()` command for vectors and regions would be nice. They could also return tidy data frames that could be filtered, examined, etc.

I'm imagining something like the following for regions:

```r
> cancensus::list_regions(dataset = "CA16") %>%
>   filter(level %in% c("CMA", "PR"), province == "British Columbia")
```
Would yield
```
# # A tibble: 8 x 5
#   region level                 name         province
#    <chr> <chr>                <chr>            <chr>
# 1  59915   CMA              Kelowna British Columbia
# 2  59925   CMA             Kamloops British Columbia
# 3  59930   CMA           Chilliwack British Columbia
# 4  59932   CMA Abbotsford - Mission British Columbia
# 5  59933   CMA            Vancouver British Columbia
# 6  59935   CMA             Victoria British Columbia
# 7  59938   CMA              Nanaimo British Columbia
# 8  59970   CMA        Prince George British Columbia
# 9  59       PR     British Columbia British Columbia
```
For vectors it could be even more simple: `list_vectors(dataset = "CA16")` could return a two-column data frame with the `vector` and its accompanying `description`.

**Comment by dshkol** [comment]
Working on this over the next few days

**Comment by mountainMath** [comment]
For the vectors, I am trying to understand what the most convenient/useful format in R would be. For other uses I am using this form https://censusmapper.ca/api/v1/vector_info/CA16, but I don't think this will work well with R. For R I am now thinking of sending this as an array of hashes (vector of lists in R terms I think), together with information on how different elements relate to one another.

```
[
{"identifier":1, "key":["v_CA16_82","v_CA16_83","v_CA16_84"],"type":["Total","Male","Female"],"prop":true,"name":"20 to 24 years","units":"1","add":"1","children":[3,4,5,6,7]},
{},...
]
```
Where the "children" vector contains the identifiers of finer data, in this case the counts for the individual ages 20,21,22,23,24. In this case the vectors come down as an array of three to denote the variables for the total count, male only and female only as indicated in the "type" variable. I could also split the total, male, female variables all out into individual array elements, but I have a feeling it is probably simpler this way. 

A slight variation on this scheme would be to send this down as a "list of lists", i.e.
```
{
1:{"key":["v_CA16_82","v_CA16_83","v_CA16_84"],"type":["Total","Male","Female"],"prop":true,"name":"20 to 24 years","units":"1","add":"1","children":[3,4,5,6,7]},
2:{"key": ....},
3: ....
}
```
where the identifiers are the keys in the list.

Any thoughts on this?

**Comment by dshkol** [comment]
Can you collapse the json tree hierarchy into a single n by m long table
with n levels of hierarchy?

**Comment by mountainMath** [comment]
Can be done. Or maybe with an extra "level" column that specifies the indentation depth of each variable. That requires the order to be fixed to parse properly, and is probably quite inefficient to e.g. query all leafs of a give node. But if that works better for R I can do that.

Also of note is that I currently have "organizing" entries without a "key" field but a "name" field that help organize the variables into categories. And in some cases I repeat "key" fields for the same purpose. You can see that in the CensusMapper variable picker. I can strip these, but it is probably good to keep some of that organizing structure.

**Comment by dshkol** [comment]
Would something like this be feasible?
```
Parent | Children | Children | Children | Children
Var | A | A | A | A
Var | A | A | A | B
Var | A | A | A | C
Var | A | A | B | A
Var | A | A | B | B
Var | A | A | B | C
Var | A | B | A | A
Var | A | B | A | B
Var | A | B | A | C
Var | A | B | B | A
Var | A | B | B | B
Var | A | B | B | C
Var | B | A | A | A
Var | B | A | A | B
Var | B | A | A | C
Var | B | A | B | A
Var | B | A | B | B
Var | B | A | B | C
Var | B | B | A | A
Var | B | B | A | B
Var | B | B | A | C
Var | B | B | B | A
Var | B | B | B | B
Var | B | B | B | C
```

**Comment by mountainMath** [comment]
If we do single variables, so not grouping total, male, female there are examples with easily over 100 children. Might be better to just have a single column with a "parent" id since each element has at most one parent. But that makes it cumbersome to traverse the graph.

There must be a standard way to store hierarchical dataset in R?

**Comment by atheriel** [comment]
There are a few ways of storing graph objects, yes, but I think that's overkill in this case, because I can't imagine anyone will want to compute over nodes.

Data frames are going to much more intuitive to work with, even if they lose some of the information. I think that four columns should be fine: `vector`, `group` (what is called "type" in the JSON object), `description`, and `parent_vector`. This means one row per vector, which is basically the "tidy" approach people will expect -- even if that means quite a large object.

**Comment by atheriel** [comment]
Also, it looks like we will need to compute the `description` by pasting together some information from the parent vectors.

**Comment by mountainMath** [comment]
I added a flattened version of the hierarchy at https://censusmapper.ca/api/v1/vector_info/CA16.csv (the json version is still available at https://censusmapper.ca/api/v1/vector_info/CA16.json). Let me know if/how that works for the R side of things.

**Comment by atheriel** [comment]
This mostly looks good to me. Two questions: (1) what is the `add` column? and (2) is there a pre-existing mapping of `units` to plain-language?

**Comment by dshkol** [comment]
Query for https://censusmapper.ca/api/v1/vector_info/CA06.csv fails in both browser and within R

**Comment by dshkol** [comment]
Also, units is not meaningful for CA11 - empty for the entire dataset.

**Comment by mountainMath** [comment]
I need to clean up some of the server data to properly send down this info. It requires manually going through the data and editing, so might take a bit. Will also fix the CA06 issues.

For the `add` flag, this concerns how the variable should be aggregated if one wants to combine values for several regions.

* 0: can't add
* 1: add
* 2: average format: 2.baseVar
* 3: median format: 3.baseVar

For the `units` variables we have
* 1: number
* 2: percentage (as ratio, e.g. 0.35 for 35%)
* 3: currency
* 4: ratio
* 5: percentage 100, e.g. 35 for 35%

If we want to be fancy, number and currency can be read in as integer type, percentage, ratio and percentage 100 as numeric.

**Comment by dshkol** [comment]
We can recode the numbers on the client side. Pretty easy - I just added that to @atheriel 's latest PR in commit #36 .

**Comment by dshkol** [comment]
I also have a very early search_vectors function ready to go to piggy back off of list_vectors. Parts of it are inelegant and could use some rework, but I quite like other parts of it. It incorporates a little bit of fuzzy matching to help people find what they're looking for, and provides info on the full hierarchy. I'll PR it after #36 is approved.

**Comment by mountainMath** [comment]
There is another variable that might be useful that I am not sending down right now. It's a 0/1 flag that indicates whether all children nodes can be interpreted as being a partition. I use that in CensusMapper to decide if I can display values as a pie (or proportional ring) chart, like for example the age variable. 

When you click into a region and select the "more" button on CensusMapper, you will see that the starburst graph automatically adjusts to a "proportional" view where it makes sense. I can see that that information might also come in useful in R when building visualizations.

Should I add it?

**Comment by dshkol** [comment]
I think it's ok, unless you really want to have that in. I can't see when someone would use that.

**Comment by mountainMath** [comment]
I added an endpoint for region discovery in csv format.

https://censusmapper.ca/data_sets/CA16/place_names.csv

The columns are
["name","geo_uid","type","population","flag"]
type is the aggregation level, flag identifies to the municipal status of the CSD, needed to for example distinguish the District of North Vancouver and City of North Vancouver. Both of these have place name "North Vancouver", but respective flags "DM" and "CY".

It's one download of all CSD, CD, CMA, PR and C with population over 5000. We should cache this to use for local searches and filtering.

**Comment by atheriel** [comment]
That looks perfect. We could cache it, or even include a bundled up version within the package distribution itself. I will take a look at this tonight.

**Comment by dshkol** [comment]
Prototypes now in master
