### ISSUE TITLE
Column names should be clear, meaningful, and thoughtfully ordered

### ISSUE THREAD

**Issue by atheriel** [mountainMath/cancensus#28]
At the moment a basic `load` call like the following

```r
census_data <- cancensus::cancensus.load(
  dataset='CA16', regions='{"PR":["59"]}',
  vectors = c("v_CA16_408"),
  level='CD'
)
```

Returns a the following `sf` object:

```
# Simple feature collection with 39 features and 18 fields
# geometry type:  MULTIPOLYGON
# dimension:      XY
# bbox:           xmin: -123.4319 ymin: 49.00193 xmax: -122.4091 ymax: 49.57428
# epsg (SRID):    4326
# proj4string:    +proj=longlat +datum=WGS84 +no_defs
# # A tibble: 39 x 19
#          a     t    dw    hh      id   pop              name  pop2  rgid  rpid  ruid   Type     `Region Name` `Area (sq km)` Population Dwellings Households
#  *   <chr> <chr> <chr> <chr>   <chr> <chr>             <chr> <chr> <chr> <chr> <chr> <fctr>            <fctr>          <dbl>      <dbl>     <dbl>      <dbl>
#  1 0.28012   CSD   286   285 5915825   471         Matsqui 4   498    59  5915 59933    CSD         Matsqui 4        0.28012        471       286        285
#  2 0.53308   CSD     4     4 5915810    10        Musqueam 4     5    59  5915 59933    CSD        Musqueam 4        0.53308         10         4          4
#  3 0.02195   CSD    25    22 5915805    54       Coquitlam 1    39    59  5915 59933    CSD       Coquitlam 1        0.02195         54        25         22
#  4 1.05651   CSD   932   920 5915806  1855   Burrard Inlet 3  1472    59  5915 59933    CSD   Burrard Inlet 3        1.05651       1855       932        920
#  5 0.27764   CSD   178   160 5915807   576         Mission 1   574    59  5915 59933    CSD         Mission 1        0.27764        576       178        160
#  6 1.79039   CSD  1433  1309 5915808  2931        Capilano 5  2700    59  5915 59933    CSD        Capilano 5        1.79039       2931      1433       1309
#  7 0.58363   CSD    16    15 5915809    49 Barnston Island 3    47    59  5915 59933    CSD Barnston Island 3        0.58363         49        16         15
#  8 0.49049   CSD    40    37 5915811   123   Seymour Creek 2   107    59  5915 59933    CSD   Seymour Creek 2        0.49049        123        40         37
#  9 0.30729   CSD    15    15 5915813    40          Katzie 2     0    59  5915 59933    CSD          Katzie 2        0.30729         40        15         15
# 10 1.78376   CSD    32    32 5915816    94 McMillan Island 6    68    59  5915 59933    CSD McMillan Island 6        1.78376         94        32         32
# # ... with 29 more rows, and 2 more variables: `v_CA16_408: Occupied private dwellings by structural type of dwelling data` <dbl>, geometry <simple_feature>
```

There are quite a number of duplicate columns here with unhelpful names; the order looks pretty arbitrary; and some of the columns clearly have the wrong type.

My suggestion for the appropriate result is the transformation (abusing `dplyr` here for illustration):

```r
df %>%
  mutate_at(vars(Households, Dwellings, Population), funs(as.integer)) %>%
  select(id, name, level = t, pop = Population, area = `Area (sq km)`,
         dwellings = Dwellings, households = Households, starts_with("v_"))
```

```
# Simple feature collection with 39 features and 8 fields
# geometry type:  MULTIPOLYGON
# dimension:      XY
# bbox:           xmin: -123.4319 ymin: 49.00193 xmax: -122.4091 ymax: 49.57428
# epsg (SRID):    4326
# proj4string:    +proj=longlat +datum=WGS84 +no_defs
# # A tibble: 39 x 9
#         id              name level   pop    area dwellings households
#      <chr>             <chr> <chr> <int>   <dbl>     <int>      <int>
#  1 5915825         Matsqui 4   CSD   471 0.28012       286        285
#  2 5915810        Musqueam 4   CSD    10 0.53308         4          4
#  3 5915805       Coquitlam 1   CSD    54 0.02195        25         22
#  4 5915806   Burrard Inlet 3   CSD  1855 1.05651       932        920
#  5 5915807         Mission 1   CSD   576 0.27764       178        160
#  6 5915808        Capilano 5   CSD  2931 1.79039      1433       1309
#  7 5915809 Barnston Island 3   CSD    49 0.58363        16         15
#  8 5915811   Seymour Creek 2   CSD   123 0.49049        40         37
#  9 5915813          Katzie 2   CSD    40 0.30729        15         15
# 10 5915816 McMillan Island 6   CSD    94 1.78376        32         32
# # ... with 29 more rows, and 2 more variables: `v_CA16_408: Occupied private dwellings by
# #   structural type of dwelling data` <dbl>, geometry <simple_feature>
```

We should also explain these columns in the help entry.

**Comment by mountainMath** [comment]
Yes, the current output is due to a) tapping into CensusMapper API that are also used for mapping on CensusMapper and b) my poor R skills.

I have experimented with some code that does some of that, but can no doubt be streamlined.

For the name changes
```
# change names
name_change <- tibble(old=c("id","a" ,"t" ,"dw","hh","id","pop","pop2"),
                   new=c("GeoUID","Shape Area" ,"Region Type" ,"Dwellings","Households","GeoUID","Population","Adjusted Population (previous Census)"))
old_names <- names(geo)
for (x in intersect(old_names,name_change$old)) {
  old_names[old_names==x]<-name_change$new[name_change$old==x]
}
names(geo)<-old_names
```

And for casting the types
```
as_character=c("GeoUID","rpid","rgid","ruid","rguid")
as_numeric=c("Shape Area","Population","Households","Dwellings","Adjusted Population (previous Census)")
geo <- geo %>% 
  mutate_at(intersect(names(geo),as_numeric),funs(as.numeric))  %>% 
  mutate_at(intersect(names(geo),as_character),funs(as.character))
```
I also have some code to deal with the
```
c("rpid","rgid","ruid","rguid")
```
variables. These represent how the region in question relates to higher levels in the geographic hierarchy, and are dependent on the level of the geography in question. In the long run, I should change how the server deals with these variables, but that will also require changes in other code and will take some time to implement. For now, it would be helpful to do the appropriate name changes in R. As the interface also allows downloading of regions of mixed type (e.g. some regions CSD level and some CT level), this may lead to space columns. Some (ugly code) example code that might work for the case when all regions are of the same type:
```
new=NULL
if (type=='DB') {new=c('DA_UID','CSD_UID','CT_UID','CMA_UID')}
if (type=='DA') {new=c('CSD_UID','CD_UID','CT_UID','CMA_UID')}
if (type=='CT') {new=c('CSD_UID','CD_UID','CT_UID','CMA_UID')}
if (type=='CSD') {new=c('CD_UID','PR_UID','CMA_UID','rguid')}

if (length(new)>0) {
  name_change <- tibble(old=c("rpid","rgid","ruid","rguid"),new=new)
  old_names=names(geo)
  for (x in intersect(old_names,name_change$old)) {
    old_names[old_names==x]<-name_change$new[name_change$old==x]
  }
  names(geo)<-old_names
}
```

**Comment by dshkol** [comment]
For renaming, the `dplyr::rename` function is very straightforward. For example:

`name_change <- tibble(old=c("id","a" ,"t" ,"dw","hh","id","pop","pop2"),
                   new=c("GeoUID","Shape Area" ,"Region Type" ,"Dwellings","Households","GeoUID","Population","Adjusted Population (previous Census)"))
old_names <- names(geo)
for (x in intersect(old_names,name_change$old)) {
  old_names[old_names==x]<-name_change$new[name_change$old==x]
}
names(geo)<-old_names`

Could be done as:

`geo <- geo %>%
  rename("GeoUID" = id,
         "Shape Area" = a,
         "Region Type" = t,
         "Dwellings" = dw,
         "Households" = hh,
         "Population" = pop,
         "Adj Population (prior Census)" = pop2)
 `

**Comment by mountainMath** [comment]
Probably easy, but I could not figure out how to use rename() while keeping the variable names flexible.  I should really pick up an introductory R book...

**Comment by dshkol** [comment]
How much do the variable names change in this case?

**Comment by mountainMath** [comment]
They change from dataset to dataset. And also from one level to another. For example, pop2 only exists for CA16 at CT level or higher. That's why I used the intersect() to cut down to the ones that are needed while keeping things simple by just defining one list for the name changes.

**Comment by dshkol** [comment]
If the majority remain across datasets, can put the rest with conditional
renames in the same pipe?

**Comment by atheriel** [comment]
I just want to chime in to suggest that (1) columns in data frames are by convention `snake_case`; and (2) that columns should be `integer` and not `numeric` when possible. Lots of these data are essentially "count data", and so those columns should be cast `as.integer`.

**Comment by atheriel** [comment]
Also, (3) those `r*` columns are pretty useless if they just contain the identifiers. I would remove them unless they could be made to contain the names of those parent regions instead.

**Comment by mountainMath** [comment]
Once we have the vector data information set up we can query that to determine the exact type, numeric or integer, of each variable and set it accordingly.

We need the geo_uids from the r* columns for some type of analysis. For example, the dot-density example that I added should utilized this to use DB geographic regions to refine the dot positions, and it should use CT level data to pick up under-counting at the DA level. To do that, it needs to know how these regions are nested.

**Comment by atheriel** [comment]
That's a fair point.

**Comment by mountainMath** [comment]
Did some work on the naming, de-duping (and type casting) of columns in https://github.com/mountainMath/cancensus/pull/35. 

Have not addressed the ordering.

**Comment by dshkol** [comment]
Implemented
