### ISSUE TITLE
Prefer ggplot2 to tmap in vignettes and README

### ISSUE THREAD

**Issue by atheriel** [mountainMath/cancensus#46]
As discussed in #44, it does not seem desirable to use `tmap`. So we should remove it in favour of `ggplot2` examples.

**Comment by dshkol** [comment]
Change to readme included in #48

**Comment by mountainMath** [comment]
We can just take the example out completely, there is a ggplot version right after. Or we can explicitly load the package in the vignette. What I like about the `tmap` example is that you get a map with just one line of code. So maybe we make a separate vignette with just the `tmap` example, aimed at minimal lines of R code?

**Comment by atheriel** [comment]
I don't feel strongly about this one way or another, to be honest.
