### ISSUE TITLE
Regions list for invalid datasets gives strange errors

### ISSUE THREAD

**Issue by atheriel** [mountainMath/cancensus#47]
This is due to the fact that if you query the API for an invalid dataset, like

https://censusmapper.ca/data_sets/CA17/place_names.csv

You get a malformed CSV file with no content instead of some sort of error. I don't know whether it is possible to check for this issue on the server side, or if we should implement validation for the `dataset` parameter on the client side to prevent this issue.

**Comment by dshkol** [comment]
I think it makes more sense to implement it on the client side. The number of datasets available is pretty limited, so its not hard to throw up errors if they don't meet it.

**Comment by mountainMath** [comment]
I can easily send down a proper error from the server. Same format as for the other requests so we can use our standard error handler.

**Comment by mountainMath** [comment]
The server now sends town an error message that displays in R as
```
Error in cancensus.handle_status_code(response, cache_file) : 
  Download of Census Data failed. Invalid Dataset Parameter 
```
There is an additional error about not being able to delete the cached file, we can probably silence that.

**Comment by atheriel** [comment]
That looks great. The cache deletion is probably due to the different internal/external caching implementation -- I'll take a look at it.
