### ISSUE TITLE
Convenience functions

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cancensus#52]
I can think of a couple of convenience function that we might want to add.

* Take a subset of the regions_list array (filtered by the user) and turn it into a region object needed for the `cancensus` load calls.
* Given a (list of) vector(s), or rows from the list_vectors csv, get all children rows from list_vectors
* Given a list of vectors or rows from list_vectors csv, select all leaves (i.e. elements without children)

I can imagine that at least I will use these quite a bit, not sure about others. Should we add `cancensus` function to do this?

**Comment by atheriel** [comment]
I have an idea for the first one, I'll submit something shortly.

**Comment by atheriel** [comment]
See #53.

**Comment by mountainMath** [comment]
I have cumbersome ways of doing the other two in my vignette, there are probably nicer ways to achieve the same thing.

**Comment by dshkol** [comment]
Yeah, after going through your vignette in my patch #57 I think we should add a function to recursively pull out children. It would be pretty useful.

**Comment by mountainMath** [comment]
The outstanding part should be addressed in https://github.com/mountainMath/cancensus/issues/52.
