### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by mountainMath** [mountainMath/cancensus#62]
We are making quite heavy use of caching, and I am wondering if we should either have a separate convenience function where we can bundle that code or use a package for caching.

Also, the this code
```
cache_dir <- system.file("cache/", package = "cancensus")
```
does not seem to be doing anything, at least for me.

**Comment by atheriel** [comment]
It's supposed to return the filepath of the `cache` directory *within* the package source itself. It's possible that it is not working because an empty `cache` directory is not being copied over from `inst/cache` properly -- I may have bungled that in a commit somewhere.

I agree that we should refactor out some sort of `cache_location` function.

**Comment by mountainMath** [comment]
Good call to store the data for the packages centrally instead of separately in each directory where the package is used. Hopefully https://github.com/mountainMath/cancensus/pull/63 addresses the issue of the missing cache directory.

Wondering too now if we should centralize the cache for the data files too. It's less transparent for the user if the cache is out of sight, but it saves time, storage space and API points if same requests are made from different projects/directories.

**Comment by atheriel** [comment]
We could potentially have a `cancensus.cache_locally` option (`FALSE` by default) that would store them in the current directory, as opposed to in the package itself, for users that might want that kind of behaviour.

On a related note, I started working on factoring out all the caching code into a central location (handling failure more gracefully) last night; should finish it later today.

**Comment by mountainMath** [comment]
I am starting to wonder though if we should just cache the metadata for the current R session only. That way it's always quite fresh and we don't have to worry about stale objects. The load on the server is too much an issue for that, I cache the metadata queries on the server, especially the region list query that takes some time to assemble all the region data.

The census data we should definitely keep caching, that hits the database with every request, they are hard to cache on the server because there are so many possibilities of variables/regions to query. And they count against the API points.

**Comment by atheriel** [comment]
We could change the default for `list_*` functions so that `use_cache = FALSE`.

**Comment by mountainMath** [comment]
That would work. Then the cache is a fallback for working offline. We should still do session caching, otherwise the search and filter functions will keep hitting the server and slow stuff down unnecessarily. Not sure how session caching works in R. Just define a global variable? Or use the "options" like we do with the API key?

**Comment by atheriel** [comment]
Probably the search/filter functions would pass `use_cache = TRUE` explicitly to prevent repeat calls. I can also look at adding a `quietly` parameter to suppress warnings/messages about cache use.

R does have session caching (through, most often the [**memoise** package](https://cran.r-project.org/web/packages/memoise/index.html)), but I don't think it's a great fit here.

**Comment by atheriel** [comment]
We can also use `curl::has_internet()` to check if a user is connected, and set the default caching behaviour appropriately. `curl` is imported by `httr`, so this wouldn't add a new dependency.

**Comment by mountainMath** [comment]
That would certainly make it fail quite gracefully in case of being offline. So how about the following strategy for metadata:

check cached file, if older then one day and have internet connection, update the cached file

If we additionally avoid calling the `list_census_vectors` function multiple times within e.g. `parent_census_vectors` then we only have one disk read per user function call.

**Comment by dshkol** [comment]
Jumping in here late, but this seems like overengineering to me. Having data available offline through the package is really cool - but it's not an expectation that anyone has of an R package. Anyone planning to access online data (i.e. through an API) in R would just access it when connected and store for later use. 

I measured the size of the metadata objects (for the '16 data, at least). 
* Datasets came in at 1752 bytes
* Regions came in at 147672 bytes
* Vectors came in at 265312 bytes

So a total of less than 0.5MB. 

Why not just package the metadata with the package and access it from there? As STC releases more data over the next three months (last release is scheduled for November), we can code those dates in there to prompt people to update their dataset by running versions of the list_* functions on the backend to update the data. 

Updated data can also be packaged with the library itself, which will surely see updates for other reasons before the end of the year.

**Comment by atheriel** [comment]
I disagree that we don't have to think fairly carefully about caching, especially for non-metadata, although I think you are right in that we don't need the perfectly engineered solution from the outset. (The "code those dates" solution looks just as complicated to me as the other options) And @mountainMath is correct in pointing out that the server load for these cached queries is low.

But I **do** agree we should provide pre-cached metadata in the package itself for distribution. I suspect you've only measured the 2016 data, but FWIW, we can use `save(..., compress = "xz")` to get smaller files, and distribute the 2006 and 2011 ones as well. CRAN won't accept packages with more than 5MB of data, but we should be under that without issue.

**Comment by mountainMath** [comment]
One reason for offline access is that people that like to use this for reproducible analysis will have some of the list_census_regions or list_census_vectors call in their code, just like we have in the vignettes. That means that every time they make changes later on in the analysis they may run the queries again. And this will introduce a time delay and will break when offline unless it is cached.

I don't think packaging the metadata is a good idea. Datasets update regularly. I just added two cross-tabulations, still testing them before adding them to the dataset api. StatCan just pulled the language data because it had issues, and is slowly trickling corrected language data. I don't think we should rely on people updating their `cancensus` installation to get the new metadata. If we have functionality for the user to update the metadata anyway then there is no need to package it in the first place.

I think the whole point  of having an R package is that it takes some of those choices away from the user. The step of checking for a working internet connection may have only marginal benefit, but it's only one line of code. The rest of the caching is quite important I think.

**Comment by dshkol** [comment]
Points well taken.

**Comment by atheriel** [comment]
I think we can close this now!

**Comment by dshkol** [comment]
Addressed in #67 , #68 , and #70
