### ISSUE TITLE
Travis-CI Integration

### ISSUE THREAD

**Issue by atheriel** [mountainMath/cancensus#72]
I think this would be nice to add, but since I don't own the repository I can't set it up myself. If we enable it I'm happy to work on the configuration.

Fair warning, though: `R CMD check` fails pretty hard on the vignettes on my local machine, so it would likely fail at the outset on Travis as well.

**Comment by dshkol** [comment]
The vignettes all need updating at this point. I've been distracted from finishing up my documntation pieces, but this is a good reminder. 

As far as continuous integration... sure? That's out of my wheelhouse in terms of why it would be beneficial.

**Comment by mountainMath** [comment]
I think that's a good idea, especially when we already are having trouble keeping the vignettes up to date (probably my bad). Will get this set up.

**Comment by mountainMath** [comment]
Ok, we are hooked up. I think. No configuration file yet, @atheriel do you want to have a go and get it set up?
