### ISSUE TITLE
Possible vignette amalgamation

### ISSUE THREAD

**Issue by atheriel** [mountainMath/cancensus#78]
I've been working on fixing vignette builds for Travis, and it has occured to me that the four existing vignettes (plus the `README`) cover pretty similar ground. It might be better to amalgamate the existing ones into a single, longer vignette (or perhaps two) with more subsections. I don't think "more is better" really applies here, since most people will probably only read one vignette.

The `README` file can then highlight a single cool example, and then link to the hosted vignette sections for more info.

It is also possible that some of the existing examples, particularly the thoughtful or complex ones, would make better blog posts than vignette content. It's not unusual to point to blog posts in the `README` file, either.

Thoughts on this? Should I try amalgamating the vignettes myself? And how should this relate to #65?

**Comment by mountainMath** [comment]
I am pretty happy to follow your and @dshkol's lead on this, I don't have much experience with how R packages are usually structured and what people expect from vignettes.

**Comment by dshkol** [comment]
Hey guys, just got back from the woods. It's a gorgeous end of summer here, and trying to take advantage as much as possible. 

On #65, I have most of the the way through a vignette/documentation page about the different features cancensus has for importing data (datasets, regions, variable search and selection, etc.), looking something like this: http://rmarkdown.rstudio.com/html_document_format.html.

**Comment by atheriel** [comment]
I consider this closed by #99.
