### ISSUE TITLE
Census Variable Labels 

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#86]
We're currently providing people with the option to return short census vector variables when using the parameter `labels = short` in calling `get_census(...)`. Somewhere along the way, the functionality I built in during an earlier branch to store and return the detailed variables was lost, but we're still making reference to it in the documentation. 

The previous functionality was called via `cancensus.labels()` which doesn't appear to be in the master code anymore. I think it's a pretty useful feature when working with short form variable names, and easy enough to implement, so I'm wondering if we removed that on purpose or by accident. If an accident, we can re-insert it where appropriate. 

If anyone has a suggestion for a better way of handling the variable descriptions, feel free to comment.

**Comment by mountainMath** [comment]
It still exists, called `census_vectors` after the Big Renaming operation. One quibble I have is that the attributes seem to get lost on when piping. So I if I want to use the labels I first have to pull in the data and store it, then grab the labels, then continue to process.

**Comment by dshkol** [comment]
I guess we missed something in the great renaming. I'll do a quick PR to fix that in the documentation and we can return to address the other issues here a bit later.
