### ISSUE TITLE
Force load spatial library if spatial data selected

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cancensus#94]
When downloading census data using `get_census` with `sf` spatial format, one has to have already loaded the `sf` library, otherwise the resulting data object will be a `tbl_df` with a `geometry` variable rather than an `sf` class object.  This can lead to all sorts of problems when doing any operations on that data, such as transformation or summarization or plotting. 

Something to look at. I imagine it's bad practice to force load the `sf` library with the `get_census` call if the user selects the `sf` format?

**Comment by mountainMath** [comment]
Looks to me like it's a bug within `read_sf`. Maybe we should just file a bug report and wait it out? And flag it in the documentation.

**Comment by mountainMath** [comment]
Or is the issue that `sf::read_sf(geo_file)` reads it into the correct format and some of the later transformations we do screw things up?

**Comment by atheriel** [comment]
I think that's more likely the cause: based on some unrelated testing, I noticed that `transform_geo()` will not always return an `sf` object.

We can add an `st_as_sf()` call (I think that's the right one, can't remember offhand) afterwards to resolve this. I had a branch around somewhere that did this, but I'm not sure what happened to it.

**Comment by dshkol** [comment]
Is this still outstanding?

**Comment by mountainMath** [comment]
Yes, I am still getting that issue at times. I think we can address that by specifying the appropriate `sf` methods that overload `dplyr`. Or by just casting it into an `sf` object before handing it to the user.

**Comment by mountainMath** [comment]
Just ran into this again, this is  still is an issue. This can be solved by adding an `sf::st_as_sf` cast before returning an sf object if the `geo_fromat='sf'` options was chosen.

**Comment by dshkol** [comment]
Maybe what it should do is load the `sf` library if that format is selected and `sf` isn't loaded yet, and if `geo_format='sf'` is selected but the package is not available, to throw an error. Something simple like: 
if(geo_format == "sf" & "sf" %in% rownames(installed.packages())) {require(sf)} etc..

**Comment by dshkol** [comment]
Implemented a fix for `get_census` in the 'sf-require-fix' branch using @mountainMath 's suggested revision https://github.com/mountainMath/cancensus/tree/sf-require-fix

**However**: it doesn't seem to fix `get_census_geometry`, which should function like `get_census` with no vectors, but I can't figure out where in the code it's being despatialized. If @mountainMath can take a look to see where that is going wrong, I would appreciate it.

**Comment by dshkol** [comment]
This was fixed in #114
